---

title: "Estimation of Quantile Regressions with Multiple Fixed Effects"
shorttitle: "Short toc Here"
author: 

    - name: Fernando Rios-Avila
      email: friosavi@levy.org
      affiliations:
        - name: Levy Economics Institute
          city: Annandale-on-Hudson, NY 
    - name: Leonardo Siles
      email: lsiles@fen.uchile.cl
      affiliations:
      - name: Universidad de Chile
        city: Santiago, Chile
    - name: Gustavo Canavire-Bacarreza
      email: gcanavire@worldbank.org
      affiliations:
      - name: "The World Bank"
        city: Washington, DC

shortauthor: "Rios-Avila, Siles, Canavire-Bacarreza"

aboutauthors: |
    Fernando Rios-Avila is a Research Scholar at the Levy Economics Institute of Bard College. 
    
    Gustavo Canavire-Bacarreza is a Senior Economist at the World Bank.

abstract: |
    This is an example of StataJ article made by me

keywords: Stata, LaTeX, Quarto, StataJ
format: 
    stjquarto-pdf: default
keep-tex: true        
stata:    
    vv: "vv"
    ii: "ii"
    yyyy: "yyyy"
    mm: "mm"
bibliography: "bibliography.bib"
cite-method: natbib
---

# Introduction {#sec-intro}

 Quantile regression, introduced by @koenker1978, has become an important tool in economic analysis, allowing to examine how the relationship between the dependent and independent variables varies across different points of the conditional distribution of the outcome. While ordinary least squares focuses on analyzing the conditional mean, quantile regression provides a more comprehensive view of how covariates impact the entire conditional distribution of the dependent variable. This can reveal heterogeneous effects that may be otherwise overlooked when analyzing the conditional mean. 

 A relatively recent development in the literature has focused on extending quantile regression analysis in a panel data setting to account for unobserved, but time fixed heterogeneity. This is particularly important in empirical research, where unobserved heterogeneity can bias estimates of the effects of interest. However, as it is common in the estimation of non-linear models with fixed effects, introducing fixed effects in quantile regression models poses several challenges. On the one hand, the simple inclusion of fixed effects can lead to an incidental parameter problem, which can bias estimates of the quantile coefficients [@neymanscott1948; @lancaster2000]. On the other hand, the computational complexity of estimating quantile regression models with fixed effects can be prohibitive, particularly for large datasets with multiple high-dimensional fixed effects. While many strategies have been proposed for estimating this type of model (see @galvao2017quantile for a review), none has become standard due to restrictive assumptions regarding the inclusion of fixed effects and the computational complexity. 

 In spite of the growing interest in estimating quantile regression models with fixed effects in applied research, particularly in the fields of labor economics, health economics, and public policy, among others, there are few commands that allow the estimation of such models. In Stata, there are three main built-in commands available for estimating quantile regression `qreg`, `ivqregress`, and `bayes: qreg`, and none of them allow for the inclusion of fixed effects, other than using the dummy variable approach. From the community-contributed commands, there is `xtqreg`, which implements a quantile regression model with fixed effects based on the method of moments proposed by @mss2019, and more recently `xtmdqr` which implements a minimum distance estimation of quantile regression models with fixed effects described in @melly2023. In both cases, these command are constrained to a single set of fixed effects.[^1] 

 [^1]: There are other community-contributed commands like `xtrifreg`, `rifhdfe`, `qregpd`, `rqr` among others that allow for the estimation of quantile regression models, but do not estimate conditional quantile regressions, but instead focus on unconditional quantile regressions, or quantile treatment effects.

 To address this, in this paper we introduce two Stata commands for estimating quantile regressions with multiple fixed effects: `mmqreg` and `qregfe`. The first command `mmqreg` is an extension of the method of moments quantile regression estimator proposed by @mss2019. The second `qregfe`, implements three other approaches: an implementation of a correlated random effects estimator based on @abrevaya2008, @wooldridge2019 and @wooldridge2010 [Ch12.10.3]; the estimator proposed by @canay2011, and a proposed modification of this approach. In addition, we also present an auxiliary command `qregplot` for the visualization of the quantile regression models. 

 Both commands offer the advantage of allowing for the estimation of conditional quantile regressions while controlling for multiple fixed effects. First, they leverage over existing Stata commands, as well as other community-contributed commands, to allow users to estimate quantile regression models and their standard errors under different assumptions. Second, they reduce the impact of the incidental parameters problem depending on the assumptions of the underlying the data generating process. In terms of standard errors, `mmqreg` allows for the estimation of analytical standard errors (see @mss2019 and @riosavila2024), whereas `qregfe` emphasizes the use of bootstrap standard errors. Finally, both commands are designed to be user-friendly, allowing for the estimation of quantile regression models with fixed effects in a single line of code. 

 The remainder of the paper is organized as follows. Section 2 reviews the methodological framework for quantile regression. Section 3 describes the methods and formulas used by `mmqreg` and `qregfe` commands. Section 4 introduces the commands, along with a brief description of their syntax and options. Section 5 introduces an auxiliary command for the visualization of quantile regression models. Section 6 provides an empirical applications demonstrating their use. Section 7 concludes. 

 # The Basics {#sec-basics}

 Quantile regressions allow researchers to identify the heterogenous effect covariates could have over the entire conditional distribution of the dependent variable. Let $y_i$ be the dependent variable, $x_i$ the vector of covariates excluding a constant, and $0<\tau<1$ is a parameter such that $q_\tau(y_i|X)$ identifies the $\tau th$ quantile of the conditional distribution of $y_i|X$. Under the assumption that conditional quantiles are linear functions of the parameters, the quantile regression model can be written as: 

 $$q_\tau(y_i|X)=\beta_0(\tau) + x_i'\beta(\tau)
$${#eq-qr}

 Where $\beta(\tau)$ is the vector of coefficients that may vary across $\tau$ and needs to be estimated, and $x_i$ is a vector of exogenous covariates that may include nonlinear functions of underlying variables. This expression indicates that, conditional on $x$, the $\tau$-th quantile of $y$ can be approximated by a linear function of $X$. 

 Under the assumption that the conditional quantile function is linear and correctly specified, a useful way to think about the data generating process is to consider the following model: 

 $$y_i = \beta_0(U_i)+x_i'\beta(U_i) 
$${#eq-dgp}

 where $U_i$ is a random variable that follows a uniform distribution. It can be seen as the rank an individual belongs to among all individuals with the same characteristics. In addition, $\beta_0$ and $\beta(U_i)$ are smooth functions that depend on $U_i$.[^2] 

 [^2]: This way of thinking about quantile regression coefficients is similar to the use of Smooth varying coefficient models, except that the running variable is not observed.

 As explained in @wooldridge2010, the coefficient of quantile regression models can be identified by minimizing the following loss function, with respect to $\beta(\tau)$: 

 $$
\hat\beta_0(\tau),\hat\beta(\tau) = \min_{\beta(\tau)} \sum_{i=1}^{n} \rho_\tau \big(y_i-\beta_0(\tau)-x_i'\beta(\tau)\big)
$${#eq-qloss}

 Where $\rho_\tau(u)=u\big(\tau-I(u<0)\big)$ is the check function, and $I(\cdot)$ is the indicator function. In essence, quantile regressions are estimating the parameters locally around the $\tau$-th quantile, although other approaches are possible [^3]. 

 [^3]: @kaplan2017 for example uses a nonparametric approach that produces smooth set of beta coefficients. And @bottai2019, proposes methods for estimating parametric quantile regression models, impossing parametric restrictions on the quantile coefficients across the distribution.

 Most commands for estimating quantile regression models focus on estimating the above loss function, using linear programming techniques, while others like @kaplan2017 (`sivqr`) and @chernozhukov2022 (`qrprocess`) use other optimization techniques. 

 When no unobserved heterogeneity is present, quantile regression model can be easily implemented in a panel setting (see @wooldridge2010), using a pooled version of the model. However, when unobserved heterogeneity is present explicitly, the estimation of quantile regressions is more challenging. Consider the case of panel data and the following data generating process: 

 $$y_{it} = \beta_0(U_{it}) + x_{it}'\beta(U_{it}) + \alpha_i(U_{it})
$${#eq-dgp-panel}

 Where $U_{it}$ is a random variable that follows a uniform distribution, and $\alpha_i(U_{it})$ is the unobserved effect that varies across individuals. In this case, the conditional quantile regression model can be written as: 
$$q_\tau(y_{it}|x_{it},\alpha_i(\tau))=\beta_0(\tau) + x_{it}'\beta(\tau)+\alpha_i(\tau) 
$${#eq-feqr} 

 This specification is explicitly considering that the unobserved effect is identified for each $i_{th}$ observation, and that it varies across quantiles ($\alpha_i(\tau)$). A common approach used, yet incorrect due to the incidental parameter problem, is to estimate this model by adding dummy variables for each individual in the quantile regression model (as in @budig2001), or by demeaning the explanatory variables (as in @budig2010). In contrast with standard linear models, there is no transformation of the data that can eliminate the individual fixed effects for non-linear models like quantile regressions. 

 In this framework, the problem of the incidental parameter problem occurs because the unobserved factors cannot be differenced out of. In other words, unless specific assumptions are made, the estimation requires the explicit estimation of the unobserved fixed effect. Unfortunately, because the number of available observations per individual fixed effect is limited, they cannot be estimated with precision. In turn, the cumulative errors in the estimation of the fixed effects will also affect the conditional distribution of the outcome, which quantile regressions leverage on, leading to inconsistent estimates of all parameters. [^4] 

 [^4]: This is similar to the measuring error problem of dependent variables in quantile regression models discussed in @hausman2021.

 In the next section, we present a few solutions and implementations for the estimation of quantile regression models with multiple fixed effects. 

 ## Correlated Random Effects: CRE {#sec-cre}

 The first approach we discuss is the use of Correlated Random Effects (CRE) models for the estimation of quantile regression models. The CRE model is an alternative methodology for the estimation of fixed effects models that was proposed by @mundlak1978 and later generalized by @chamberlain1982. In contrast with standard fixed effects, the approach allows users to control for time fixed covariates in addition to time-varying covariates. And, in contrast with the random effects model, it does not make the assumption that the unobserved effect is uncorrelated with the observed covariates. Interestingly, in the context of linear models, the CRE model is equivalent to the fixed effects model [@wooldridge2010].