---
title: "Estimation of Quantile Regressions with Multiple Fixed Effects"
shorttitle: "Short toc Here"
author: 

    - name: Fernando Rios-Avila
      email: friosavi@levy.org
      affiliations:
        - name: Levy Economics Institute
          city: Annandale-on-Hudson, NY 
    - name: Leonardo Siles
      email: lsiles@fen.uchile.cl
      affiliations:
      - name: Universidad de Chile
        city: Santiago, Chile
    - name: Gustavo Canavire-Bacarreza
      email: gcanavire@worldbank.org
      affiliations:
      - name: "The World Bank"
        city: Washington, DC

shortauthor: "Rios-Avila, Siles, Canavire-Bacarreza"

aboutauthors: |
    Fernando Rios-Avila is a Research Scholar at the Levy Economics Institute of Bard College. 
    
    Gustavo Canavire-Bacarreza is a Senior Economist at the World Bank.

abstract: |
    This is an example of StataJ article made by me

keywords: Stata, LaTeX, Quarto, StataJ
format: 
    stjquarto-pdf: default
keep-tex: true        
stata:    
    vv: "vv"
    ii: "ii"
    yyyy: "yyyy"
    mm: "mm"
bibliography: "bibliography.bib"
cite-method: natbib
---

# Introduction {#sec-intro}

Quantile regression, introduced by @koenker1978, has become an important tool in economic analysis, allowing to examine how the relationship between the dependent and independent variables varies across different points of the conditional distribution of the outcome. While ordinary least squares focuses on analyzing the conditional mean, quantile regression provides a more comprehensive view of how covariates impact the entire conditional distribution of the dependent variable. This can reveal heterogeneous effects that may be otherwise overlooked when analyzing the conditional mean.

A relatively recent development in the literature has focused on extending quantile regression analysis in a panel data setting to account for unobserved, but time fixed heterogeneity. This is particularly important in empirical research, where unobserved heterogeneity can bias estimates of the effects of interest. However, as it is common in the estimation of non-linear models with fixed effects, introducing fixed effects in quantile regression models poses several challenges. On the one hand, the simple inclusion of fixed effects can lead to an incidental parameter problem, which can bias estimates of the quantile coefficients [@neymanscott1948; @lancaster2000]. On the other hand, the computational complexity of estimating quantile regression models with fixed effects can be prohibitive, particularly for large datasets with multiple high-dimensional fixed effects. While many strategies have been proposed for estimating this type of model (see @galvao2017quantile for a review), none has become standard due to restrictive assumptions regarding the inclusion of fixed effects and the computational complexity.

In spite of the growing interest in estimating quantile regression models with fixed effects in applied research, particularly in the fields of labor economics, health economics, and public policy, among others, there are few commands that allow the estimation of such models. In Stata, there are three main built-in commands available for estimating quantile regression `qreg`, `ivqregress`, and `bayes: qreg`, and none of them allow for the inclusion of fixed effects, other than using the dummy variable approach. From the community-contributed commands, there is `xtqreg`, which implements a quantile regression model with fixed effects based on the method of moments proposed by @mss2019, and more recently `xtmdqr` which implements a minimum distance estimation of quantile regression models with fixed effects described in @melly2023. In both cases, these command are constrained to a single set of fixed effects.[^1]

[^1]: There are other community-contributed commands like `xtrifreg`, `rifhdfe`, `qregpd`, `rqr` among others that allow for the estimation of quantile regression models, but do not estimate conditional quantile regressions, but instead focus on unconditional quantile regressions, or quantile treatment effects.

To address this, in this paper we introduce two Stata commands for estimating quantile regressions with multiple fixed effects: `mmqreg` and `qregfe`. The first command `mmqreg` is an extension of the method of moments quantile regression estimator proposed by @mss2019. The second `qregfe`, implements three other approaches: an implementation of a correlated random effects estimator based on @abrevaya2008, @wooldridge2019 and @wooldridge2010 [Ch12.10.3]; the estimator proposed by @canay2011, and a proposed modification of this approach. In addition, we also present an auxiliary command `qregplot` for the visualization of the quantile regression models.

Both commands offer the advantage of allowing for the estimation of conditional quantile regressions while controlling for multiple fixed effects. First, they leverage over existing Stata commands, as well as other community-contributed commands, to allow users to estimate quantile regression models and their standard errors under different assumptions. Second, they reduce the impact of the incidental parameters problem depending on the assumptions of the underlying the data generating process. In terms of standard errors, `mmqreg` allows for the estimation of analytical standard errors (see @mss2019 and @riosavila2024), whereas `qregfe` emphasizes the use of bootstrap standard errors. Finally, both commands are designed to be user-friendly, allowing for the estimation of quantile regression models with fixed effects in a single line of code.

The remainder of the paper is organized as follows. Section 2 reviews the methodological framework for quantile regression. Section 3 describes the methods and formulas used by `mmqreg` and `qregfe` commands. Section 4 introduces the commands, along with a brief description of their syntax and options. Section 5 introduces an auxiliary command for the visualization of quantile regression models. Section 6 provides an empirical applications demonstrating their use. Section 7 concludes.

# The Basics {#sec-basics}

Quantile regressions allow researchers to identify the heterogenous effect covariates could have over the entire conditional distribution of the dependent variable. Let $y_i$ be the dependent variable, $x_i$ the vector of covariates, and $0<\tau<1$ is a parameter such that $q_\tau(y_i|X)$ identifies the $\tau th$ quantile of the conditional distribution of $y_i|X$. Under the assumption that conditional quantiles are linear functions of the parameters, the quantile regression model can be written as:

$$q_\tau(y_i|X)=x_i\beta(\tau)
$$ {#eq-qr}

Where $\beta(\tau)$ is the vector of coefficients that may vary across $\tau$ and needs to be estimated, and $x_i$ is a vector of exogenous covariates that may include nonlinear functions of underlying variables. This expression indicates that, conditional on $X$, the $\tau$-th quantile of $Y$ can be approximated by a linear function of $X$.

As explained in @wooldridge2010, the coefficient of quantile regression models can be identified by minimizing the following loss function, with respect to $\beta(\tau)$:

$$
\hat\beta(\tau) = \min_{\beta(\tau)} \sum_{i=1}^{n} \rho_\tau \big(y_i-x_i\beta(\tau)\big)
$$ {#eq-qloss}

Where $\rho_\tau(u)=u\big(\tau-I(u<0)\big)$ is the check function, and $I(\cdot)$ is the indicator function.

Most commands for estimating quantile regression models focus on estimating the above loss function, using linear programming techniques, while others like @kaplan2017 (`sivqr`) and @chernozhukov2022 (`qrprocess`) use other optimization techniques.

When no unobserved heterogeneity is present, quantile regression model can be easily implemented in a panel setting (see @wooldridge2010), using a pooled version of the model. However, when unobserved heterogeneity is present explicitly, the estimation of quantile regressions is more challenging. Consider the case of panel data such that the conditional quantile regression model is given by:

$$q_\tau(y_{it}|X_{it},1_i)=x_{it}\beta(\tau)+\alpha_i(\tau) 
$$ {#eq-feqr}

This specification is explicitly considering that the unobserve effect is identified for each $i_{th}$ observation, and that this effect varies across quantiles ($\alpha_i(\tau)$). A common approach, yet incorrect due to the incidental parameter problem, is to estimate this model by adding dummy variables for each individual in the quantile regression model (as in @budig2001), or by demeaning the explanatory variables (as in @budig2010). In fact, there is no transformation of the data that can eliminate the individual fixed effects, as it happens in standard linear regression models.

In this framework, the problem of the incidental parameter problem occurs because the unobserved factors cannot be differenced out of. In other words, unless specific assumptions are made, the estimation requires the explicit estimation of the unobserved fixed effect. Unfortunately, because the number of available observations per individual fixed effect is limited, they cannot be estimated with precision. In turn, the cumulative errors in the estimation of the fixed effects will also affect the conditional distribution of the outcome, which quantile regressions leverage on, leading to inconsistent estimates of all parameters. [^2]

[^2]: This is similar to the measuring error problem of dependent variables in quantile regression models discussed in @hausman2021.

In the next section, we present a few solutions and implementations for the estimation of quantile regression models with multiple fixed effects.

## Correlated Random Effects: CRE {#sec-cre}

The first approach we discuss is the use of Correlated Random Effects (CRE) models for the estimation of quantile regression models. The CRE model is an alternative methodology for the estimation of fixed effects models that was proposed by @mundlak1978 and later generalized by @chamberlain1982. In contrast with standard fixed effects, the approach allows users to control for time fixed covariates in addition to time-varying covariates. And, in contrast with the random effects model, it does not make the assumption that the unobserved effect is uncorrelated with the observed covariates. Interestingly, in the context of linear models, the CRE model is equivalent to the fixed effects model [@wooldridge2010].

Consider the following model:

$$y_{it} = x_{it}\beta + z_{i}\gamma + \alpha_i + u_{it}
$$ {#eq-cre-1}

It is well known that if $\alpha_i$ is correlated with $x_{it}$, the Random Effects (RE) estimator will be inconsistent. This is similar to the ommited variable bias. The solution proposed by @mundlak1978 and @chamberlain1982 was to explicitly account for that correlation in the model, by assuming the unobserved effect $\alpha_i$ is a linear projection of the observed time-varying variables. Specifically:

$$\begin{aligned}
Mundlack:  & & \alpha_i &= \gamma_0 + \bar x_{i}\gamma + v_i&  \\
Chamberlain: & & \alpha_i &= \gamma_0 + x_{i1}\gamma_1 + x_{i2}\gamma_2 + \dots + x_{iT}\gamma_T + v_i 
\end{aligned}
$$ {#eq-cre-2}

The main difference between both approaches was that Chamberlain's is more flexible by allowing all realizations of the time-varying variables to explain the unobserved effect. In contrast, Mundlak's approach only considers the average of the time-varying variables, which is a more restrictive specification. Using either model specification, if we substitute @eq-cre-2 into @eq-cre-1, the final model can be written as:

$$y_{it} = x_{it}\beta + z_{i}\gamma + \gamma_0 + f(x_{it})\Gamma + v_i + u_{it}
$$ {#eq-cre-final}

where $f(x_{it})$ can be the full set of time-varying variables or just the average of them. Interestingly, either method provides the same results if the panel data is balanced, and all covariates are strictly exogenous. However, this identity breaks down in other cases (see @abrevaya2013). 

The strategy proposed by @abrevaya2008 was to extend the CRE model (@chamberlain1982 style) for the estimation of quantile regression models. This, however, has some limitations. First, when the number of periods is large, the number of additional regressors grows quickly, which can lead to other problems during estimation. Second, while the application of @chamberlain1982 projection approach for unbalance data is possible (see @abrevaya2013), it is not straightforward to implement in practice, specially for the framework of quantile regression. Instead, we follow @wooldridge2010 and @wooldridge2019, and use the Mundlak representation of the CRE model for the estimation of quantile regression models. @wooldridge2019 has shown that this can be easily applied for cases with unbalanced panels, and the estimation of non-linear models.

Specifically, @wooldridge2010 suggests that we could estimate the quantile regression model using the Mundlak representation of the CRE model:

$$q_\tau(y_{it}|x_{it},\bar x_i)=x_{it}\beta(\tau)+\bar x_i\gamma(\tau) 
$$

One of the benefits from this approach is that it will not only allow to easily use unbalanced panels, but may also provide an approach to control for multiple fixed effects, as discussed in @baltagi2023. For example, for a case with two dimensions of fixed effects (say individual and time), we could model each time varying variable as follows:

$$x^k_{it}-E(x_{it}^k)=\lambda^{xk}_i + \lambda^{xk}_t + \varepsilon_{it}
$$

Here, we use the centered transformation of the explanatory variable, that is $x^k_{it}-E(x_{it}^k)$, so that all $\lambda's$ have an expected value of zero. Also, $\lambda^{xk}_i$ and $\lambda^{xk}_t$ are the equivalent to $\bar x_i$ in the Mundlak one-way fixed effects model, and they can be obtained using an iterative process similar to @rios2015 or @correia_feasible_nodate.^[Internally, we use @correia_feasible_nodate `reghdfe` to obtain the predicted fixed effects] The final model can be written as:

$$q_\tau(y_{it}|x_{it},\lambda_i^x,\lambda_t^x)=x_{it}\beta(\tau)+\lambda^x_i\gamma_i(\tau)+\lambda^x_t\gamma_t(\tau)  
$$

Which could be extended to any number of fixed effects.

## Canay (2011) Estimator {#sec-canay}

The second approach under consideration is the estimator proposed by @canay2011. This paper argues that the estimator proposed by @abrevaya2008, and thus the implementation described above, may not provide consistent estimates of the quantile regression coefficients, as long as there is a disturbance $\varepsilon_{it}$ left after modeling @eq-cre-2. However, under the assumption that the unobserved effect is a pure location shift, that is $\alpha_i$ does not vary across quantiles, they propose that a two-step estimator can be used to consistently estimate the quantile regression coefficients. The first one eliminating the unobserved fixed effect, and the second one estimating the quantile coefficients.

To better understand how this estimator works, let us consider the following data generating process (DGP):

$$y_{i} =\beta_0(\rho_{i}) +  \beta_1(\rho_{i}) x_{1i} + \beta_2(\rho_{i}) x_{2i} 
$$

This represents the random coefficient approach to quantile regression models, where the coefficients of the model are allowed to vary as a function of a random variable $\rho_{i}$, which follows a uniform distribution. $\rho_i$ is unobserved, but it is assumed to be independent of the covariates. Given this DGP, the conditional quantile function can be written as:

$$q_{\tau}(y_{i}|x_{1i},x_{2i}) = \beta_0(\tau) + \beta_1(\tau) x_{1i} + \beta_2(\tau) x_{2i}$$

In this specification, the impact of $x_{k}$ on $y$ is allowed to vary across quantiles. However, we could also impose the assumption that some of the coefficients are constant across quantiles. For example, if $\beta_2(\tau)=\beta_2$ for all $\tau$, we would be assuming that $x_2$ only has a location effect on $y$. In fact, if all coefficients (but $\beta_0$) are constant across quantiles, the model could just as well be estimated using OLS. And under this scenario, it may be convenient to estimate the model imposing this restriction in the model. This is the main idea behind the Canay estimator.

The estimator proposed by @canay2011 imposes the assumption that the unobserved effect is a pure location shift. More explicit, assumes that the data generating process in a panel data setting, can be written as follows:
$$y_{it} =\beta_0(\rho_{it}) +  \beta_1(\rho_{it}) x_{it} + \alpha_i
$$

According to @canay2011, under the assumption that $\alpha_i$ is constant across quantiles, we could consistently estimate the quantile regression coefficients $\beta{\tau}$, by simply transforming the dependent variable as follows:

$$y_{it}-\alpha_i =\tilde y_{it}=\beta_0(\rho_{it}) +  \beta_1(\rho_{it}) x_{it} 
$$

And then use standard quantile methods on $\tilde{y}_{it}$. More formally, he suggests the following two-step estimator:

1.  Using an OLS regression, run the following model:
$$y_{it} = x_{it}\beta + \alpha_i + \varepsilon_{it}$$

and esitmate $\hat{\alpha}_i$.^[Empirically, this can be done using `reghdfe` command.]

2. Transform the dependent variable as $\tilde y_{it}=y_{it}-\hat{\alpha}_i$, and estimate the quantile regression model:

$$q_{\tau}(y_{it}-\hat \alpha_i|x_{it})=q_{\tau}(\tilde y_{it}|x_{it}) = x_{it}\beta(\tau)$$

This simple approach allows for the identification of the quantile coefficients, by imposing the assumption that the unobserved effect is a pure location shift. And like the CRE model, it can be extended to multiple fixed effects, as long as one is willing to assume that the unobserved effects are pure location shifts. For example, consider a case with two fixed effects dimensions (individual and time), the model could be written as:

$$y_{it} = x_{it}\beta + \alpha_i + \alpha_t + \varepsilon_{it}$$

As before $\alpha_i$ and $\alpha_t$, assumed constant across quantiles, could be estimated using OLS, and the quantile regression model estimated using the transformed dependent variable.

$$q_{\tau}(y_{it}-\hat \alpha_i - \hat \alpha_t|x_{it})=q_{\tau}(\tilde y_{it}|x_{it}) = x_{it}\beta(\tau)
$$

Which again can be easily estimated using standard quantile regression methods.

## Modified Canay(2011) Estimator {#sec-mcanay}

Perhaps one of the main limitations of the Canay estimator is that it assumes that the unobserved effect is a pure location shift. If this assumption is violated, it may lead to inconsistent estimates of the quantile coefficients. To address this limitation, we propose a small modification to the Canay estimator.

We start by assuming that the unobserved effect represents some characteristics of the individual that are constant across quantiles, and that can be compared across individuals. Under this consideration, the data generating process can be written as:

$$y_{it} =\beta_0(\rho_{it}) +  \beta_1(\rho_{it}) x_{it} + \gamma(\rho_{it}) \alpha_i
$$

Next, similar to @canay2011, we propose to estimate the unobserved effect $\alpha_i$ using OLS, and assume that, in average the $E[\gamma(\rho_{it})]=1$. Up to this point, the estimator is the same as the Canay estimator. However, we propose that instead of imposing $\gamma(\rho_{it}) \alpha_i$ to be constant across quantiles, we allow for the prediction of the unobserved effect $\alpha_i$ to vary across quantiles. This can be done by estimating the following model:

$$q_{\tau}(y_{it}|x_{it},\hat \alpha_i) =  x_{it}\beta(\tau)+\gamma(\tau) \hat\alpha_i
$$

As before, this model can be extended to multiple fixed effects, by simply estimating the unobserved effects using OLS, and then estimating the quantile regression model using the predicted unobserved effects. The main advantage over @canay2011 is that this estimator allows for the unobserved effect to have a different impact on the dependent variable across quantiles, which may be more realistic in many applications. However, it assumes the OLS estimator does allow for the consistent estimation of an unobserved effect that is comprarable across individuals, which may not always be the case.

## Method of Moments Quantile Regression @mss2019 {#sec-mmqr}

This approach of estimating regression quantiles with multiple fixed effects distinguishes itself from the other estimators reviewed above in the sense that [@mss2019] introduce location-scale effects of fixed effects upon the distribution of interest. Compared to Canay's estimator, the Method of Moments Quantile Regression (MMQREG) not only allows the $\alpha_i$'s to affect $Y_{it}$ through location shifts, but rather MMQREG is able to identify the scale shifts that alter different points of the distribution belonging to $Y$.

We begin by defining the DGP of the location scale model:

$$Y_{it} = \alpha_i + X_{it}' \beta + (\delta_i + X_{it}' \gamma) u_{it}
$$ {#eq-dgp_mmqreg}

Where parameters $\alpha_i$ and $\delta_i$ capture the individual fixed effects. Note that, compared to equation [\[eq:dgp_canay\]](#eq:dgp_canay){reference-type="ref" reference="eq:dgp_canay"}, the fixed effects not only enter the model in an additive fashion, instead they also have a multiplicative effect upon the error term. In addition, the $U_{it}$ are i.i.d. across $i$ and $t$, statistically independent of $X_{it}$ and satisfy $E(U) = 0$ and $E(|U|) = 1$ both of which normalize the random variable.

Our location scale model in equation [\[eq:dgp_mmqreg\]](#eq:dgp_mmqreg){reference-type="ref" reference="eq:dgp_mmqreg"} implies that:

$$\label{eq:mmqreg_quantile}
    Q_{\tau}(Y_{it}|X_i) = [\alpha_i + \delta_i q(\tau)] + X_{it}' \beta + X_{it}' \gamma q(\tau)$$

Where the scalar coefficient $\alpha_i(\tau) \equiv \alpha_i + \delta_i q(\tau)$ is the quantile-$\tau$ fixed effect for individual $i$, which represent how time-invariant variables have *different impacts on different regions* of the conditional distribution of $Y_{it}$. However, our real interest is in the regression quantile coefficients:

$$\label{eq:rqcoefficients_mmqreg}
    \beta_{\tau} = \beta + q(\tau) \gamma$$

Which are simply a linear combination of the location coefficients ($\beta$) and the scale coefficients ($\gamma$), where the second vector of coefficients is weighted by the value of the $\tau$-th quantile of the variable of interest $Y_{it}$. [@mss2019] develop the following algorithm for implementing the MMQREG estimator:

1.  Obtain $\hat{\beta}_k$ by regressing time-demeaned $Y_{it}$ on time-demeaned controls $X_{it}$, i.e. obtain $\hat{\beta}$ by the within estimator.

2.  Estimate the $\hat{\alpha}_i$'s and calculate the residuals $\hat{R}_{it} = Y_{it} - \hat{\alpha}_i - X_{it}' \hat{beta}$.

3.  Obtain $\hat{\gamma}_k$ by the within estimator using $|\hat{R}_{it}|$ as the dependent variable.

4.  Estimate $\hat{\delta}_i$ by taking the time average of $|\hat{R}_{it}| - X_{it}' \hat{\gamma}$.

5.  Estimate $q(\tau)$ by $\hat{q}$, which corresponds to the regression quantile of standardized residuals \[$\hat{R}_{it}/(\hat{\gamma}_{i} + X_{it}' \hat{\gamma})]$ upon an intercept term.

Note that Steps 1 and 2 from the MMQREG algorithm are the same as those performed in Canay's estimator. However, the location-scale model used in [@mss2019] adds three additional steps that are required to estimate $\hat{\gamma}$ and $\hat{q}$, so that regression quantile coefficients $\beta_{\tau}$ are allowed to affect not only the location of the distribution, but also its shape.

Add notes on the assumptions of MMQREG here *if* necessary.

Statistical inference can be performed using the asymptotic distribution of the estimator derived in [@mss2019]. Expanding on this literature, [@riosavila2024] propose methods for computing alternative standard errors using the empirical influence functions of the estimators. Robust and clustered standard errors can be estimated following this approach, and are readily available as options in the `mmqreg` command in Stata. Another extension of the MMQREG estimator due to [@riosavila2024] is to allow for the inclusion of multiple fixed effects using an application of the Frisch-Waugh-Lovell (FWL) theorem to partial out the effect of variables capturing unobserved heterogeneity from both dependent and explanatory variables. Likewise, the command `mmqreg` allows for multiple fixed effects, as will be shown next.

| Column 1 | Column 2 | Column 3 |
|----------|----------|----------|
| Data 1   | Data 2   | Data 3   |
| Data 4   | Data 5   | Data 6   |

: Government spending and coalition government - MMQREG Estimator

As we allow for both location and scale shifts in our estimation method, the monotonic pattern observed in the first row of table [3](#tab:mcanay_results){reference-type="ref" reference="tab:mcanay_results"} is reversed. Now, the farther we move from the median of the distribution in the direction of greater government spending, the lower is the effect of a permanent change from single-party to coalition upon spending. The median coefficient, once again, remains close to the mean coefficient (2.36) under MMQREG estimation. Results from table [4](#tab:mmqreg_results){reference-type="ref" reference="tab:mmqreg_results"} support the conclusions from [@persson2007] regarding types of government and its spending during the last year of legislature, expanding the results to the response of the distribution of spending upon changes in explanatory variables.

We must also note that statistical inference ---with robust standard errors displayed in table [4](#tab:mmqreg_results){reference-type="ref" reference="tab:mmqreg_results"}--- for the [@persson2007] dataset show that many coefficients that with the previous estimators were not statistically different from zero, are now significant even at the 99% confidence level. This is due to the ability to compute robust standard errors for the MMQREG estimator, contrasting with the CRE and Canay estimators, for which we estimated the covariance matrix using the bootstrap. Although not displayed here, our findings are robust to clustering standard errors for country so that the coefficients of 25th and 50th quantiles corresponding to the indicator variable for coalition government remain statistically significant.

# Conclusions {#sec:conclusions}